# Generated by Django 4.0.3 on 2022-08-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='task',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
