# Generated by Django 4.0.3 on 2022-08-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingModel',
        ),
    ]
