# Generated by Django 4.0.3 on 2022-08-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_alter_ratingmodel_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='elearn.learner'),
        ),
    ]
