# Generated by Django 4.0.3 on 2022-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0006_alter_ratingmodel_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
