# Generated by Django 4.0.3 on 2022-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0008_remove_profile_progress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
