# Generated by Django 4.0.3 on 2022-09-06 18:17

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0015_quillpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
