# Generated by Django 4.0.3 on 2022-09-06 18:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0016_alter_tutorial_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
