# Generated by Django 4.0.3 on 2022-09-07 20:09

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0017_delete_quillpost_alter_tutorial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video2',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video3',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
